apiVersion: v1
kind: Service
metadata:
  name: webapps-nginx-ingress-controller-svc
  namespace: default
  annotations:
    gitrepo: webapps-app-nginx-ingress
  labels:
    app: webapps-nginx-ingress-controller

spec:
  clusterIP: ''
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30110
  - name: https
    port: 443
    targetPort: 443
    nodePort: 30111
  selector:
    app: webapps-nginx-ingress-controller
    name: webapps-nginx-ingress-controller-dp
    product: webapps
  type: NodePort
