apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapps-nginx-ingress-controller-dp
  namespace: default
  annotations:
    gitrepo: webapps-app-nginx-ingress
  labels:
    app: webapps-nginx-ingress-controller
    name: webapps-nginx-ingress-controller-dp
    product: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapps-nginx-ingress-controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapps-nginx-ingress-controller
        name: webapps-nginx-ingress-controller-dp
        product: webapps
      annotations:
        prometheus.io/port: '10254'
        prometheus.io/scrape: 'true'
      name: webapps-nginx-ingress-controller
    spec:
      serviceAccountName: nginx-ingress-serviceaccount
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        lifecycle:
          preStop:
            exec:
              command:
              - sleep
              - '2'
        image: docker-nginx-jwt-12
        name: webapps-nginx-ingress-controller
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        args:
        - "/nginx-ingress-controller"
        - "--configmap=webapps/webapps-nginx-ingress-controller"
        - "--default-backend-service=webapps/webapps-nginx-ingress-default-backend-svc"
        - "--watch-namespace=default"
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/healthz"
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/healthz"
            port: 10254
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
